package yorubik.model;
// Generated 17-mar-2017 3:57:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private double dnf;
     private Date createdAt;
     private Date updatedAt;

    public Category() {
    }

	
    public Category(String name, double dnf) {
        this.name = name;
        this.dnf = dnf;
    }
    public Category(String name, double dnf, Date createdAt, Date updatedAt) {
       this.name = name;
       this.dnf = dnf;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getDnf() {
        return this.dnf;
    }
    
    public void setDnf(double dnf) {
        this.dnf = dnf;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return this.name;
    }


}


