package yorubik.model;
// Generated 17-mar-2017 3:57:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cuber generated by hbm2java
 */
public class Cuber  implements java.io.Serializable {


     private int id;
     private Date birthday;
     private String name;
     private byte[] template;

    public Cuber() {
    }

    public Cuber(Date birthday, String name, byte[] template) {
       this.birthday = birthday;
       this.name = name;
       this.template = template;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte[] getTemplate() {
        return this.template;
    }
    
    public void setTemplate(byte[] template) {
        this.template = template;
    }

    @Override
    public String toString() {
        return this.name;
    }


}


