package yorubik.model;
// Generated 17-mar-2017 3:57:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Judge generated by hbm2java
 */
public class Judge  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date bornDate;
     private byte[] digit;
     private String photo;
     private Date createdAt;
     private Date updatedAt;

    public Judge() {
    }

	
    public Judge(String name, Date bornDate) {
        this.name = name;
        this.bornDate = bornDate;
    }
    public Judge(String name, Date bornDate, byte[] digit, String photo, Date createdAt, Date updatedAt) {
       this.name = name;
       this.bornDate = bornDate;
       this.digit = digit;
       this.photo = photo;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBornDate() {
        return this.bornDate;
    }
    
    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }
    public byte[] getDigit() {
        return this.digit;
    }
    
    public void setDigit(byte[] digit) {
        this.digit = digit;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return this.name;
    }


}


