package yorubik.model;
// Generated 17-mar-2017 3:57:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rounds generated by hbm2java
 */
public class Round  implements java.io.Serializable {


     private Integer id;
     private double avg;
     private double pb;
     private Integer tournamentId;
     private Integer judgeId;
     private Integer cuberId;
     private Integer categoryId;
     private Date createdAt;
     private Date updatedAt;

    public Round() {
    }

	
    public Round(double avg, double pb) {
        this.avg = avg;
        this.pb = pb;
    }
    
    public Round(Integer tournamentId, Integer judgeId, Integer cuberId, Integer categoryId) {
        this.tournamentId = tournamentId;
        this.judgeId = judgeId;
        this.cuberId = cuberId;
        this.categoryId = categoryId;
    }
    
    public Round(double avg, double pb, Integer tournamentId, Integer judgeId, Integer cuberId, Integer categoryId, Date createdAt, Date updatedAt) {
       this.avg = avg;
       this.pb = pb;
       this.tournamentId = tournamentId;
       this.judgeId = judgeId;
       this.cuberId = cuberId;
       this.categoryId = categoryId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getAvg() {
        return this.avg;
    }
    
    public void setAvg(double avg) {
        this.avg = avg;
    }
    public double getPb() {
        return this.pb;
    }
    
    public void setPb(double pb) {
        this.pb = pb;
    }
    public Integer getTournamentId() {
        return this.tournamentId;
    }
    
    public void setTournamentId(Integer tournamentId) {
        this.tournamentId = tournamentId;
    }
    public Integer getJudgeId() {
        return this.judgeId;
    }
    
    public void setJudgeId(Integer judgeId) {
        this.judgeId = judgeId;
    }
    public Integer getCuberId() {
        return this.cuberId;
    }
    
    public void setCuberId(Integer cuberId) {
        this.cuberId = cuberId;
    }
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "Round{" + "id=" + id + ", avg=" + avg + ", pb=" + pb + ", tournamentId=" + tournamentId + ", judgeId=" + judgeId + ", cuberId=" + cuberId + ", categoryId=" + categoryId + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + '}';
    }

}


