package yorubik.model;
// Generated 17-mar-2017 3:57:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Times generated by hbm2java
 */
public class Time  implements java.io.Serializable {


     private Integer id;
     private double time;
     private String reason;
     private double dnf;
     private double plus;
     private int iteration;
     private int roundId;
     private Date createdAt;
     private Date updatedAt;

    public Time() {
    }

	
    public Time(double time, String reason, double dnf, double plus, int iteration, int roundId) {
        this.time = time;
        this.reason = reason;
        this.dnf = dnf;
        this.plus = plus;
        this.iteration = iteration;
        this.roundId = roundId;
    }
    public Time(double time, String reason, double dnf, double plus, int iteration, int roundId, Date createdAt, Date updatedAt) {
       this.time = time;
       this.reason = reason;
       this.dnf = dnf;
       this.plus = plus;
       this.iteration = iteration;
       this.roundId = roundId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getTime() {
        return this.time;
    }
    
    public void setTime(double time) {
        this.time = time;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public double getDnf() {
        return this.dnf;
    }
    
    public void setDnf(double dnf) {
        this.dnf = dnf;
    }
    public double getPlus() {
        return this.plus;
    }
    
    public void setPlus(double plus) {
        this.plus = plus;
    }
    public int getIteration() {
        return this.iteration;
    }
    
    public void setIteration(int iteration) {
        this.iteration = iteration;
    }
    public int getRoundId() {
        return this.roundId;
    }
    
    public void setRoundId(int roundId) {
        this.roundId = roundId;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "Time{" + "id=" + id + ", time=" + time + ", reason=" + reason + ", dnf=" + dnf + ", plus=" + plus + ", iteration=" + iteration + ", roundId=" + roundId + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + '}';
    }


}


